### ISSUE TITLE
'build' document search token conflicts with yeoman/grunt-usemin

### ISSUE THREAD

**Issue by jimjamjoh** [spatools/grunt-html-build#3]
The yeoman/grunt-usemin module uses the same html comment search syntax as this project to identify parseable sections.  e.g.

&lt;!-- build:js js/app.js --&gt;

It is currently impossible to configure a project to use both grunt-html-build and grunt-usemin due to this conflict.  Please make the token 'build' configurable via a Gruntfile to enable a different parse token for grunt-html-build, e.g.

&lt;!-- htmlbuild:section views --&gt;

Thanks, this is a great project otherwise!

**Comment by lpaulger** [comment]
it seems that this change has been reverted in 0.1.6? Is there a recommended way to handle this?

**Comment by SomaticIT** [comment]
You can change __build__ tag by using __parseTag__ option. 
[See documentation](https://github.com/spatools/grunt-html-build/wiki/Task-Options#optionsparsetag)
