### ISSUE TITLE
Recursive html building

### ISSUE THREAD

**Issue by nlfurniss** [spatools/grunt-html-build#31]
Is there a way to have the src html built recursively?

For example, if many pages use build:section layout.base, and the base has build:section layout.header, the header won't be processed and left as a comment

**Comment by cssagogo** [comment]
This sounds cool, but I'm not sure I follow the usage example in the documentation? 

So using this...
```
    <!-- build:section recursive views -->
    <!-- /build --> 
```
Outputs...
```
        <div id="view1">...</div>
        <div id="view2">...</div>
        <div id="view3">...</div>
```
And if you have build comments inside the views they will get processed as if they were inline?

I can see some use for that, but what I'm trying to wrap my head around is how best to handle a multipage site.  What would the setup for that look like?  Do I have to create a new entry for each new page in the grunt task?  Can I reuse options between the pages?

**Comment by SomaticIT** [comment]
You seems to understand well the feature but i'm not sure I understand of your project.
Can you detail it?
Thanks
