### ISSUE TITLE
How to use absolute url ?

### ISSUE THREAD

**Issue by monkeymonk** [spatools/grunt-html-build#42]
Hi there,

I'm trying to add `//maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places` but it seems that is not working.

`gruntfile.js` part:
```
scripts: {
    head: [
        '//maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places',
        '<%= files.public_dir %>/js/vendor/jquery.js',
    ],
},
```

`index.html` part:
```
<head>
    <!-- build:script head -->
    <!-- /build -->
</head>
```

**Comment by SomaticIT** [comment]
This issue was fixed by #34.
It is included in version __0.4.1__ which is published in NPM.
