### ISSUE TITLE
Performance v0.4.0

### ISSUE THREAD

**Issue by corlletelab** [spatools/grunt-html-build#43]
I've tested your new version 0.4.0. The new recursive build feature is great, but the module is running very slow compared to the 0.3.2 version when processing/creating HTML files. Are working on this or this will stay so.

Here some logs

```
**v0.3.2**
Execution Time (2014-09-18 10:16:38 UTC)
loading tasks     3ms  ▇ 1%
htmlbuild:main  248ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 99%
Total 251ms
```

```
**v0.4.0**
Execution Time (2014-09-18 10:12:50 UTC)
htmlbuild:main  14s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 14s
```

I have 42 main HTML files and including about 40 sections. 

Thank you for your great work!

**Comment by DenEwout** [comment]
I'm also interested in the 0.4.0 version. Subscribed.

**Comment by corlletelab** [comment]
I'm not sure, but it seem that this project is dead

**Comment by SomaticIT** [comment]
Sorry, I was busy past months,

In version __0.4.1__ which will be published in npm today, a new option __recursive__ can be added to section tags to enable recursive building.

It avoid the big performance impact seen in version __0.4.0__ for most projects.

**Comment by corlletelab** [comment]
Thank you, Thank you, Thank you!!!!

**Comment by DenEwout** [comment]
Thanks!
