### ISSUE TITLE
Output multiple pages

### ISSUE THREAD

**Issue by jordanranson** [spatools/grunt-html-build#44]
I have a footer and a header and a layout plus a directory full of views. It looks like this:

* layout
    * footer.html
    * header.html
* views
    * home.html
    * search.html
    * contact.html
* index.html

index.html looks like this

```
<!-- build:section layout.header -->
<!-- /build -->

<!-- build:section views -->
<!-- /build -->

<!-- build:section layout.footer -->
<!-- /build -->
```

When I run grunt, I get a single index.html outputted with ALL VIEWS. How do I get it to generate a separate page for each view, using the same layout?

**Comment by SomaticIT** [comment]
Unfortunately there is no easy solution for your issue.
Your own solution is for me the best you can make.

**Comment by michaeltheb** [comment]
hello, there are updates about it? I would like to create many views from a base html file. thank you
