### ISSUE TITLE
Add link tag for less-files

### ISSUE THREAD

**Issue by hlynx** [spatools/grunt-html-build#45]
LESS precompiler loads files from `<link>` tag with special `rel` attribute.
According to documentation (`http://lesscss.org/`) the tag should look like this:
`<link rel="stylesheet/less" type="text/css" href="styles.less" />`

And there is no point in writing that files inline.

The possible decision may be in letting programmer to change template
`<link type="text/css" rel="stylesheet" href="<%= src %>" />`.
Is it possible?

**Comment by SomaticIT** [comment]
Thanks for your report.
In the next release `0.4.4`, I added a test for less files to automatically change the `rel` attribute.
