### ISSUE TITLE
Wrong compilation

### ISSUE THREAD

**Issue by giolvani** [spatools/grunt-html-build#53]
I don't know if this issue happens with you, but to me, the build tag just works if it is inline

this way works:
```html
    <!-- build:script login --><!-- /build -->

    <!-- build:process -->webshims.polyfill('forms forms-ext <%= version %>');<!-- /build -->
```

but this... nothing happens!
```html
    <!-- build:script login -->
    <!-- /build -->

    <!-- build:process -->
        webshims.polyfill('forms forms-ext <%= version %>');
    <!-- /build -->
```

I saw the build-html.js and I found at line 267
```javascript
content = content.replace(raw, function () { return result });
```
although the values are correct, when it tries replace, nothing happens.

For now, I will keep using the inline way...

**Comment by php-max** [comment]
same here. no compilation replacement in  multiline files.

**Comment by php-max** [comment]
finally I found the answer. Change the line ending  format of your files from `dos` to `unix` . Then it will work.

**Comment by giolvani** [comment]
Great man! 
It finally works for me.

But, it would be very nice if the lib solves it, or write it in some place of documentation!
