### ISSUE TITLE
Defer for links and scripts?

### ISSUE THREAD

**Issue by Aghassi** [spatools/grunt-html-build#58]
I looked through, but I can't seem to find it. Is there a way to make it so I can set links and scripts to have 'defer' in them? Or do I just have to do that manually? Would be much easier if you had a defer option that we could set to true or false.

**Comment by SomaticIT** [comment]
In next release `0.5.0`, you can add `defer` or `async` options in your `script` tags. e.g.:
```html
<!-- build:script defer app -->
<!-- /build -->
```
