### ISSUE TITLE
Templates outside of webroot

### ISSUE THREAD

**Issue by bradroberts** [spatools/grunt-html-build#65]
Just looking for help... sorry for creating an issue. I've used this plugin successfully in the past, but my destination files were in the web root. This time, the files I'm replacing are outside the web root. I've spent several hours trying to figure it out and read through every issue I thought was applicable, but I just can't get there.

The directory structure is:

- /Gruntfile.js
- /public (webroot)
- /public/build/css/main.min.css
- **/resources/views/layouts/default.php (layout file)** 

I'm trying to replace the following in the layout file

```
<!-- build:style main -->
<link rel="stylesheet" href="/build/css/main.dev.css">
<!-- /build -->
```

Desired result (dev replaced with min file):

```
<link type="text/css" rel="stylesheet" href="/build/css/main.min.css">
```

This is what I'm trying now:

```
htmlbuild: {
    production: {
        src: 'resources/views/layouts/**/*.php',
        options: {
            replace: true,
            prefix: '/',
            styles: {
                main: 'public/build/css/main.min.css'
            }
        }
    }
}
```

Here's the current result, which doesn't work because *public* is my web root.

```
<link type="text/css" rel="stylesheet" href="/public/build/css/main.min.css">
```

Thank you in advance for any help or direction you might have.

**Comment by mikec** [comment]
@bradroberts I had the same issue and I got it working using `relative: false` and `cwd` options. I think this config will work for you:

```
htmlbuild: {
    production: {
        src: 'resources/views/layouts/**/*.php',
        options: {
            relative: false,
            replace: true,
            prefix: '/',
            styles: {
                main: {
                    cwd: 'public',
                    files: [ 'build/css/main.min.css' ]
                }
            }
        }
    }
}
```

**Comment by SomaticIT** [comment]
Hi,
@bradroberts The solution provided by @mikec is correct. You should try it.
@mikec Thanks for your comment.
