### ISSUE TITLE
No expand capability

### ISSUE THREAD

**Issue by bturk** [spatools/grunt-html-build#69]
I tried to use expand on the files and they all dumped into the same directory.  To work with a tree of files I have to set up separate configs for each tree.

It would be nice if this supported standard grunt syntax for files:

http://gruntjs.com/configuring-tasks

**Comment by SomaticIT** [comment]
Hi,
Thanks for your report.

The new version __0.5.2__ fixes some issues in relative paths management. 
It could help with your problem. 

Can you try to update your local `grunt-html-build` version and try your build again ?
If your experience the same issue, can you provide an sample configuration ?

**Comment by bturk** [comment]
Nope, it still acts as if you specify flatten even if you don't.

html looks like:
    index.html
    views/1.html
    views/2.html
    templates/1.html
    templates/2.html

Config
```javascript
htmlbuild: {
  options: {
    relative: true,
    beautify: true,
    data: conf.htmlData
  },
  html: {
    options {
      expand: true,
      cwd: 'html'
    }
    src: 'html/**/*.html,
    dest: 'dist/'
  }
}
```

This should duplicate the file tree in dist but it flattens the tree and puts all files in the root of dist.

**Comment by SomaticIT** [comment]
Ok I understand your problem. 
There are some issues in your configuration :

````javascript
htmlbuild: {
    options: {
        relative: true,
        beautify: true,
        data: conf.htmlData
    },
    html: {
        files: [{
            expand: true,
            cwd: 'html',
            src: '**/*.html',
            dest: 'dist'
        }]
    }
}
````

**Comment by bturk** [comment]
I had tried it with/without the directory prefix on the src, neither worked.  Looks like the trick is not putting expand/cwd in options.  It's a little non-standard but it works.  Thanks for the tip.

**Comment by SomaticIT** [comment]
I'll think for a solution.
Thanks for your report.
