### ISSUE TITLE
Title tag inside SVG included in title in sitemap

### ISSUE THREAD

**Issue by depiction** [spatools/grunt-html-build#72]
I'm working on a site that needs to comply with WCAG 2.0 (https://www.w3.org/TR/WCAG20/)

In order to pass accessibility tests, SVGs need a title tag or description tag included in them. Think of it as alt text for an image. Details can be found at https://www.w3.org/TR/SVG/access.html

When using a title tag inside an SVG, the tag's content appears appended to the page's title in the HTML sitemap. It should use only the title tag in the head section.

**Comment by SomaticIT** [comment]
Hi,

Sorry for my delayed answer, I can't reproduce your issue.
Can you send me some details about your configuration ?

Thanks.
