### ISSUE TITLE
sections are only included, but not processed

### ISSUE THREAD

**Issue by IceScorpion** [spatools/grunt-html-build#80]
hi, 
i tried using variables in the sections, but the processing does not seem to work within the included files.
More detailed problem describtion can be found here: 
http://stackoverflow.com/questions/38850095/grunt-html-build-process-variable-inside-section 

Regards
IceScorpion

**Comment by SomaticIT** [comment]
You can process `sections` by using the `recursive` option: [view doc](https://github.com/spatools/grunt-html-build/wiki/Creating-HTML-Sections#recursive-option).
