### ISSUE TITLE
Suffix to css and js files

### ISSUE THREAD

**Issue by hlynx** [spatools/grunt-html-build#83]
Can you add suffix option to the found css and js files?
Such feature will really help to add version to prevent caching.

I mean build.min.js?v=2017-02-01_10-00-00

It could be a callback.

**Comment by hlynx** [comment]
Or give an option to configure templates

**Comment by SomaticIT** [comment]
Sorry for my answer delay.
It's an excellent option. It will be provided in next release.

**Comment by SomaticIT** [comment]
Hi @hlynx,

Your request has been introduced in new release `0.7.0`.
You can now specify a `suffix` option which can be a string or a function. The generated suffix is the appended to the URL in the form `{url}?{suffix}`.

More on this option : https://github.com/spatools/grunt-html-build/wiki/Task-Options#optionssuffix

Hope it helps,
Thanks
