### ISSUE TITLE
Get current dir name for inline content

### ISSUE THREAD

**Issue by Taz002** [spatools/grunt-html-build#85]
If I have the example directory, is it possible to inline the correct CSS without having a separate line for each HTML page?

```
app
 - home
   - home.html
   - home.module.js
   - home.controller.js
 - help
   - help.html
   - etc
 - styles
   - home.css
   - help.css
```

So in theory with just '/styles/%CURRENT_DIR_NAME%.css' inline task on the homepage it would pull /styles/home.css and the same task on the help page would pull /styles/help.css?

**Comment by Taz002** [comment]
I think current file name being processed is probably better. So home.html will inline it's specific page scripts/styles.

**Comment by SomaticIT** [comment]
Hi @Taz002,
I reviewed your pull request #86 and chose to extend your functionality.
I added a `processFiles` option which enable files `src` processing.

You can use the following keywords in your files `src`:
* `$(filename)`: Current filename (without extension).
* `$(file)`: Current filename (with extension).
* `$(dirname)`: Current directory name.
* `$(path)`: Current file path.
* `$(dir)`: Current directory path.
* `$(platform)`: The result of `process.platform`.

Thanks for your work.
