### ISSUE TITLE
Possibility to change the default src and dest folders

### ISSUE THREAD

**Issue by Spuffynism** [spatools/grunt-html-build#87]
In the current version, whatever I specify for the `src` path, "src" will be prefixed to the file. For example, if I specify `src: 'app/views/index.html'`, the resulting file will be `src/app/views/index.html`.

The same thing occurs with the `desc` option (e.g.`dest: 'index.html'` results in the creation of `dest/index.html`. By specifying `dest: 'index.html'`, I'd think an `index.html` file at the same level as my gruntfile would be created.
 
I have tried using the `replace` and `prefix` options, to no avail.

Is this a bug or should I make a pull request with the possibility of customizing `src` and `desc` as default folders?

**Comment by SomaticIT** [comment]
Did you try the `relative` option

**Comment by Spuffynism** [comment]
Sorry for the late reply.

I found the reason for the problems I was having: I was putting the `src`, `dest` and `options` properties directly in the `htmlbuild` object instead of making them properties of a grunt target (like `dist` in the first example of the [Task-Options](https://github.com/spatools/grunt-html-build/wiki/Task-Options) section of the documentation.)

I was doing this:
```javascript
htmlbuild: {
    src: 'index.html',
    dest: './',
    options: { ... }
}
```
instead of doing this:
```javascript
htmlbuild: {
    dev: {
        src: 'app/tpls/index.html',
        dest: './',
        options: {
    }
}
```

Thank you for your help!
