### ISSUE TITLE
Relative path linking for a collection of src doesn't work

### ISSUE THREAD

**Issue by tkoelpin** [spatools/grunt-html-build#88]
Hello,

I have now found a bug and I want to share it with you for fixing them.
In the following case when a multiple star-marker is used on the src, then the output of the source will be still the same (the relative path is generated once, not for each file).

I am using the following setting in my gruntfile: 
`

grunt.initConfig({
        
    // The fixture Path
    fixturesPath: "dist/private/",

    htmlbuild: {
        replace: {
            src: 'build/view/**/*.html',
            dest: 'dist/',
            options: {
                basePath: 'build/view/',
                scripts: {
                    bundle: [
                        '<%= fixturesPath %>/js/external-script.min.js',
                        '<%= fixturesPath %>/js/script.min.js',
                    ],
                    webhelper: '<%= fixturesPath %>/js/webhelper-script.min.js'
                },
                styles: {
                    bundle: [
                        '<%= fixturesPath %>/css/external-style.min.css',
                        '<%= fixturesPath %>/css/style.min.css'
                    ]
                },
                data: {
                    icon: '<link rel="shortcut icon" href="<%= fixturesPath %>/img/logo.ico" />'
                }
            }
        }
    }
});

`

Many thanks for your help in advance.

Greetings,
tkoelpin

**Comment by tkoelpin** [comment]
Hello programmers of grunt-html-build, 

do I have done anything wrong with my code?

How do I archive the relative links with multiple src-files? 

Many thanks in advance for your help. 

Greetings, 
tkoelpin

**Comment by SomaticIT** [comment]
Many apologizes for my answer delay...

I think you could achieve what you want by using the Grunt `expand` feature:
```javascript
grunt.initConfig({
// The fixture Path
fixturesPath: "dist/private/",

htmlbuild: {
    replace: {
        files: [{
            expand: true,
            cwd: 'build/view',
            src: '**/*.html',
            dest: 'dist'
        }],
        options: {
            basePath: 'build/view/',
            scripts: {
                bundle: [
                    '<%= fixturesPath %>/js/external-script.min.js',
                    '<%= fixturesPath %>/js/script.min.js',
                ],
                webhelper: '<%= fixturesPath %>/js/webhelper-script.min.js'
            },
            styles: {
                bundle: [
                    '<%= fixturesPath %>/css/external-style.min.css',
                    '<%= fixturesPath %>/css/style.min.css'
                ]
            },
            data: {
                icon: '<link rel="shortcut icon" href="<%= fixturesPath %>/img/logo.ico" />'
            }
        }
    }
}
});
```

**Comment by tkoelpin** [comment]
Hello @SomaticIT, thank you very much for your help.  

Sorry for my late response, I have a lot of programmatically work in my company. Now I returned back to my private project.  

Your solution helped me yet so far, but I have also a last challenge for you. Can you solve the relative path problem which I cannot solve it yet?  

I am trying to insert an &lt;a&gt;-Tag with an href-attribute, but it builds the href tag wrongly.  
E.g. it builds a href tag of the following path `dist/contact/` for `<li><a href="<%= path.distContent %>/objekte/">Unsere Objekte</a></li>` with `.../objekte/dist/objekte` instead of `../contact`.

What is wrong here? Here is my extract of the code:
    module.exports = function(grunt) {
        var path = {
            src: 'src',
            srcContent: 'src/private',
            template: 'src/private/templates',
            build: 'build',
            dist: 'dist',
            distContent: 'dist/private'
        };

     grunt.initConfig({
        
         // The fixture Path
        path: path,

        htmlbuild: {
            replace: {
                src: '<%= path.build %>/view/**/*.html',
                dest: '<%= path.dist %>/',
                files: [
                    {expand: true, cwd: '<%= path.build %>/view/', src: '<%= path.build %>/view/**/*.html', dest: '<%= path.dist %>/'}
                ],
                options: {
                    basePath: '<%= path.build %>/view/',
                    logOptions: true,
                    relative: true,
                    scripts: {
                        bundle: [
                            '<%= path.distContent %>/js/external-script.min.js',
                            '<%= path.distContent %>/js/script.min.js',
                        ],
                        webhelper: '<%= path.distContent %>/js/webhelper-script.min.js'
                    },
                    styles: {
                        bundle: [
                            '<%= path.distContent %>/css/external-style.min.css',
                            '<%= path.distContent %>/css/style.min.css'
                        ]
                    },
                    data: {
                        icon:   '<link rel="shortcut icon" href="<%= path.distContent %>/img/logo.ico" />',
                        
                        header:  '<li><a href="<%= path.distContent %>/">Startseite</a></li>' + 
                                      '<li><a href="<%= path.distContent %>/objekte/">Unsere Objekte</a></li>' + 
                                      '<li><a href="<%= path.distContent %>/belegungsplan/">Belegungsplan</a></li>' + 
                                      '<li><a href="<%= path.distContent %>/preise/">Preise</a></li>' + 
                                      '<li><a href="<%= path.distContent %>/freizeit/">Freizeitangebote</a></li>'     + 
                                      '<li><a href="<%= path.distContent %>/wissenwertes/">Wissenwertes</a></li>',
                       footer:  '<li><a href="<%= path.distContent %>/impressum/">Impressum</a></li>' + 
                                    '<li><a href="<%= path.distContent %>/datenschutz/">Datenschutzerklärung</a></li>' + 
                                    '<li><a href="<%= path.distContent %>/haftungsausschluss/">Haftungsausschluss</a></li>' + 
                                    '<li><a href="<%= path.distContent %>/kontakt/">Kontakt</a></li>' + 
                                    '<li><a href="<%= path.distContent %>/gaestebuch/">Gästebuch</a></li>'
                    }
                }
            }
        }
    }

**Comment by SomaticIT** [comment]
Hello,

Indeed, `grunt-html-build` is not able to process paths during template composition because it could not know what should be modified...

You have to make the relative process on the `Gruntfile.js` side.

Thanks
