### ISSUE TITLE
how to add canonical url using grunt

### ISSUE THREAD

**Issue by sharanraj124** [spatools/grunt-html-build#94]
I have more `html  files` I already use grunt but how to push this tag  ```<link rel="canonical" href="http://localhost:8080/index.html">```  into all my html files.

**Comment by SomaticIT** [comment]
Hello,

Sorry for the delay.

You can use two features to achieve your goal:
 * [section](https://github.com/spatools/grunt-html-build/wiki/Creating-HTML-Sections)
 * [process](https://github.com/spatools/grunt-html-build/wiki/Using-HTML-as-Template)

Thanks
